### PR TITLE
Feat/landing page

### LINKED ISSUE #2: Create Project Home Page (landing and action pages)
Frontend

### PR DESCRIPTION
**Pull request by pidoxy**
resolves #2 
* Desktop Screens

127 0 0 1_5501_favigen_templates_favigen_index html

127 0 0 1_5501_favigen_templates_favigen_index html (1)

* Tablet Screen

127 0 0 1_5501_favigen_templates_favigen_index html (2)

* Mobile Screen 

127 0 0 1_5501_favigen_templates_favigen_index html (3)

### CODE REVIEW

**Comment by Mykol5** [comment]
This looks absolutely great! @pidoxy... Only noticed the three animate symbols ain't on the mobile view.

**Review by Mykol5 — APPROVED** [review]
This makes a lot of sense.
Great work @pidoxy

**Comment by pidoxy** [comment]
> This makes a lot of sense. Great work @pidoxy



> This looks absolutely great! @pidoxy... Only noticed the three animate symbols ain't on the mobile view.

thank you, yes they aren't it looks better this way

**Review by Cofucan — APPROVED** [review]
Nice one @pidoxy,

**Pull request merged**
